name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: List files in current directory
        run: ls -a

      - name: Show package.json contents
        run: cat package.json

      - name: Run Cypress tests
        run: npx cypress run --headless

      # - name: Stop server
      #   run: kill $(jobs -p) || true
